// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit by hand.
// Run `node scripts/gen-registry.mjs` after adding content files.
import type { HubContent, GuideContent } from "@/lib/content/types";
import { communityPalmJebelAli } from "@/lib/content/communities/palm-jebel-ali";
import { beachCollection } from "@/lib/content/residences/beach-collection";
import { coralCollection } from "@/lib/content/residences/coral-collection";
import { palmCentral } from "@/lib/content/residences/palm-central";
import { buyPalmJebelAli } from "@/lib/content/intent/buy-palm-jebel-ali";
import { rentPalmJebelAli } from "@/lib/content/intent/rent-palm-jebel-ali";
import { offplanPalmJebelAli } from "@/lib/content/intent/offplan-palm-jebel-ali";
import { investorGuide } from "@/lib/content/guides/palm-jebel-ali-investor-guide";
import { prices } from "@/lib/content/guides/palm-jebel-ali-prices";
import { paymentPlans } from "@/lib/content/guides/palm-jebel-ali-payment-plans";
import { villas } from "@/lib/content/guides/palm-jebel-ali-villas";
import { vsPalmJumeirah } from "@/lib/content/guides/palm-jebel-ali-vs-palm-jumeirah";
import { developer } from "@/lib/content/guides/nakheel-palm-jebel-ali-developer";
import { amenities } from "@/lib/content/guides/palm-jebel-ali-amenities";
import { beaches } from "@/lib/content/guides/palm-jebel-ali-beaches";
import { constructionProgress } from "@/lib/content/guides/palm-jebel-ali-construction-progress";
import { dining } from "@/lib/content/guides/palm-jebel-ali-dining";
import { floorPlans } from "@/lib/content/guides/palm-jebel-ali-floor-plans";
import { forUkBuyers } from "@/lib/content/guides/palm-jebel-ali-for-uk-buyers";
import { foreignBuyers } from "@/lib/content/guides/palm-jebel-ali-foreign-buyers";
import { fronds } from "@/lib/content/guides/palm-jebel-ali-fronds";
import { goldenVisa } from "@/lib/content/guides/palm-jebel-ali-golden-visa";
import { handoverTimeline } from "@/lib/content/guides/palm-jebel-ali-handover-timeline";
import { history } from "@/lib/content/guides/palm-jebel-ali-history";
import { hotels } from "@/lib/content/guides/palm-jebel-ali-hotels";
import { howToBuyOffPlan } from "@/lib/content/guides/palm-jebel-ali-how-to-buy-off-plan";
import { location } from "@/lib/content/guides/palm-jebel-ali-location";
import { marinas } from "@/lib/content/guides/palm-jebel-ali-marinas";
import { masterplan } from "@/lib/content/guides/palm-jebel-ali-masterplan";
import { mortgage } from "@/lib/content/guides/palm-jebel-ali-mortgage";
import { projectStatus } from "@/lib/content/guides/palm-jebel-ali-project-status";
import { rentalYield } from "@/lib/content/guides/palm-jebel-ali-rental-yield";
import { resale } from "@/lib/content/guides/palm-jebel-ali-resale";
import { schools } from "@/lib/content/guides/palm-jebel-ali-schools";
import { serviceCharges } from "@/lib/content/guides/palm-jebel-ali-service-charges";
import { vsBluewaters } from "@/lib/content/guides/palm-jebel-ali-vs-bluewaters";
import { vsDistrictOne } from "@/lib/content/guides/palm-jebel-ali-vs-district-one";
import { vsDubaiIslands } from "@/lib/content/guides/palm-jebel-ali-vs-dubai-islands";
import { vsEmaarBeachfront } from "@/lib/content/guides/palm-jebel-ali-vs-emaar-beachfront";
import { vsJumeirahBay } from "@/lib/content/guides/palm-jebel-ali-vs-jumeirah-bay-island";
import { vsWorldIslands } from "@/lib/content/guides/palm-jebel-ali-vs-the-world-islands";

export const COMMUNITIES: Record<string, HubContent> = {
  "palm-jebel-ali": communityPalmJebelAli,
};
export const RESIDENCES: Record<string, HubContent> = {
  "beach-collection": beachCollection,
  "coral-collection": coralCollection,
  "palm-central": palmCentral,
};
export const INTENT_BUY: Record<string, HubContent> = {
  "palm-jebel-ali": buyPalmJebelAli,
};
export const INTENT_RENT: Record<string, HubContent> = {
  "palm-jebel-ali": rentPalmJebelAli,
};
export const INTENT_OFFPLAN: Record<string, HubContent> = {
  "palm-jebel-ali": offplanPalmJebelAli,
};
export const GUIDES: Record<string, GuideContent> = {
  "palm-jebel-ali-investor-guide": investorGuide,
  "palm-jebel-ali-prices": prices,
  "palm-jebel-ali-payment-plans": paymentPlans,
  "palm-jebel-ali-villas": villas,
  "palm-jebel-ali-vs-palm-jumeirah": vsPalmJumeirah,
  "nakheel-palm-jebel-ali-developer": developer,
  "palm-jebel-ali-amenities": amenities,
  "palm-jebel-ali-beaches": beaches,
  "palm-jebel-ali-construction-progress": constructionProgress,
  "palm-jebel-ali-dining": dining,
  "palm-jebel-ali-floor-plans": floorPlans,
  "palm-jebel-ali-for-uk-buyers": forUkBuyers,
  "palm-jebel-ali-foreign-buyers": foreignBuyers,
  "palm-jebel-ali-fronds": fronds,
  "palm-jebel-ali-golden-visa": goldenVisa,
  "palm-jebel-ali-handover-timeline": handoverTimeline,
  "palm-jebel-ali-history": history,
  "palm-jebel-ali-hotels": hotels,
  "palm-jebel-ali-how-to-buy-off-plan": howToBuyOffPlan,
  "palm-jebel-ali-location": location,
  "palm-jebel-ali-marinas": marinas,
  "palm-jebel-ali-masterplan": masterplan,
  "palm-jebel-ali-mortgage": mortgage,
  "palm-jebel-ali-project-status": projectStatus,
  "palm-jebel-ali-rental-yield": rentalYield,
  "palm-jebel-ali-resale": resale,
  "palm-jebel-ali-schools": schools,
  "palm-jebel-ali-service-charges": serviceCharges,
  "palm-jebel-ali-vs-bluewaters": vsBluewaters,
  "palm-jebel-ali-vs-district-one": vsDistrictOne,
  "palm-jebel-ali-vs-dubai-islands": vsDubaiIslands,
  "palm-jebel-ali-vs-emaar-beachfront": vsEmaarBeachfront,
  "palm-jebel-ali-vs-jumeirah-bay-island": vsJumeirahBay,
  "palm-jebel-ali-vs-the-world-islands": vsWorldIslands,
};

export const GUIDE_SLUGS = Object.keys(GUIDES);
