// AUTO-GENERATED by scripts/gen-i18n-registry.mjs — do not edit by hand.
import type { HubContent, GuideContent } from "@/lib/content/types";
import type { Locale } from "@/lib/i18n";
import { baiaLunaAr } from "@/lib/content/i18n/ar/baia-luna";
import { beachCollectionAr } from "@/lib/content/i18n/ar/beach-collection";
import { bluejayAr } from "@/lib/content/i18n/ar/bluejay";
import { buyPalmJebelAliAr } from "@/lib/content/i18n/ar/buy";
import { cobaltBeachAr } from "@/lib/content/i18n/ar/cobalt-beach";
import { communityAr } from "@/lib/content/i18n/ar/community";
import { coralCollectionAr } from "@/lib/content/i18n/ar/coral-collection";
import { coralDuneAr } from "@/lib/content/i18n/ar/coral-dune";
import { cyanSkyAr } from "@/lib/content/i18n/ar/cyan-sky";
import { foreignBuyersAr } from "@/lib/content/i18n/ar/foreign-buyers";
import { goldenVisaAr } from "@/lib/content/i18n/ar/golden-visa";
import { investorGuideAr } from "@/lib/content/i18n/ar/investor-guide";
import { locationAr } from "@/lib/content/i18n/ar/location";
import { developerAr } from "@/lib/content/i18n/ar/nakheel-palm-jebel-ali-developer";
import { oceanWhisperAr } from "@/lib/content/i18n/ar/ocean-whisper";
import { offplanPalmJebelAliAr } from "@/lib/content/i18n/ar/offplan";
import { palmCentralAr } from "@/lib/content/i18n/ar/palm-central";
import { amenitiesAr } from "@/lib/content/i18n/ar/palm-jebel-ali-amenities";
import { beachesAr } from "@/lib/content/i18n/ar/palm-jebel-ali-beaches";
import { constructionProgressAr } from "@/lib/content/i18n/ar/palm-jebel-ali-construction-progress";
import { diningAr } from "@/lib/content/i18n/ar/palm-jebel-ali-dining";
import { floorPlansAr } from "@/lib/content/i18n/ar/palm-jebel-ali-floor-plans";
import { forUkBuyersAr } from "@/lib/content/i18n/ar/palm-jebel-ali-for-uk-buyers";
import { frondsAr } from "@/lib/content/i18n/ar/palm-jebel-ali-fronds";
import { handoverTimelineAr } from "@/lib/content/i18n/ar/palm-jebel-ali-handover-timeline";
import { historyAr } from "@/lib/content/i18n/ar/palm-jebel-ali-history";
import { hotelsAr } from "@/lib/content/i18n/ar/palm-jebel-ali-hotels";
import { howToBuyOffPlanAr } from "@/lib/content/i18n/ar/palm-jebel-ali-how-to-buy-off-plan";
import { marinasAr } from "@/lib/content/i18n/ar/palm-jebel-ali-marinas";
import { masterplanAr } from "@/lib/content/i18n/ar/palm-jebel-ali-masterplan";
import { mortgageAr } from "@/lib/content/i18n/ar/palm-jebel-ali-mortgage";
import { projectStatusAr } from "@/lib/content/i18n/ar/palm-jebel-ali-project-status";
import { rentalYieldAr } from "@/lib/content/i18n/ar/palm-jebel-ali-rental-yield";
import { resaleAr } from "@/lib/content/i18n/ar/palm-jebel-ali-resale";
import { schoolsAr } from "@/lib/content/i18n/ar/palm-jebel-ali-schools";
import { serviceChargesAr } from "@/lib/content/i18n/ar/palm-jebel-ali-service-charges";
import { villasAr } from "@/lib/content/i18n/ar/palm-jebel-ali-villas";
import { vsBluewatersAr } from "@/lib/content/i18n/ar/palm-jebel-ali-vs-bluewaters";
import { vsDistrictOneAr } from "@/lib/content/i18n/ar/palm-jebel-ali-vs-district-one";
import { vsDubaiIslandsAr } from "@/lib/content/i18n/ar/palm-jebel-ali-vs-dubai-islands";
import { vsEmaarBeachfrontAr } from "@/lib/content/i18n/ar/palm-jebel-ali-vs-emaar-beachfront";
import { vsJumeirahBayAr } from "@/lib/content/i18n/ar/palm-jebel-ali-vs-jumeirah-bay-island";
import { vsWorldIslandsAr } from "@/lib/content/i18n/ar/palm-jebel-ali-vs-the-world-islands";
import { paymentPlansAr } from "@/lib/content/i18n/ar/payment-plans";
import { porcelainRosesAr } from "@/lib/content/i18n/ar/porcelain-roses";
import { pricesAr } from "@/lib/content/i18n/ar/prices";
import { redAuroraAr } from "@/lib/content/i18n/ar/red-aurora";
import { redwoodAr } from "@/lib/content/i18n/ar/redwood";
import { rentPalmJebelAliAr } from "@/lib/content/i18n/ar/rent";
import { sunsetMirageAr } from "@/lib/content/i18n/ar/sunset-mirage";
import { vsPalmJumeirahAr } from "@/lib/content/i18n/ar/vs-palm-jumeirah";
import { waveCrestAr } from "@/lib/content/i18n/ar/wave-crest";
import { baiaLunaRu } from "@/lib/content/i18n/ru/baia-luna";
import { beachCollectionRu } from "@/lib/content/i18n/ru/beach-collection";
import { bluejayRu } from "@/lib/content/i18n/ru/bluejay";
import { buyPalmJebelAliRu } from "@/lib/content/i18n/ru/buy";
import { cobaltBeachRu } from "@/lib/content/i18n/ru/cobalt-beach";
import { communityRu } from "@/lib/content/i18n/ru/community";
import { coralCollectionRu } from "@/lib/content/i18n/ru/coral-collection";
import { coralDuneRu } from "@/lib/content/i18n/ru/coral-dune";
import { cyanSkyRu } from "@/lib/content/i18n/ru/cyan-sky";
import { foreignBuyersRu } from "@/lib/content/i18n/ru/foreign-buyers";
import { goldenVisaRu } from "@/lib/content/i18n/ru/golden-visa";
import { investorGuideRu } from "@/lib/content/i18n/ru/investor-guide";
import { locationRu } from "@/lib/content/i18n/ru/location";
import { developerRu } from "@/lib/content/i18n/ru/nakheel-palm-jebel-ali-developer";
import { oceanWhisperRu } from "@/lib/content/i18n/ru/ocean-whisper";
import { offplanPalmJebelAliRu } from "@/lib/content/i18n/ru/offplan";
import { palmCentralRu } from "@/lib/content/i18n/ru/palm-central";
import { amenitiesRu } from "@/lib/content/i18n/ru/palm-jebel-ali-amenities";
import { beachesRu } from "@/lib/content/i18n/ru/palm-jebel-ali-beaches";
import { constructionProgressRu } from "@/lib/content/i18n/ru/palm-jebel-ali-construction-progress";
import { diningRu } from "@/lib/content/i18n/ru/palm-jebel-ali-dining";
import { floorPlansRu } from "@/lib/content/i18n/ru/palm-jebel-ali-floor-plans";
import { forUkBuyersRu } from "@/lib/content/i18n/ru/palm-jebel-ali-for-uk-buyers";
import { frondsRu } from "@/lib/content/i18n/ru/palm-jebel-ali-fronds";
import { handoverTimelineRu } from "@/lib/content/i18n/ru/palm-jebel-ali-handover-timeline";
import { historyRu } from "@/lib/content/i18n/ru/palm-jebel-ali-history";
import { hotelsRu } from "@/lib/content/i18n/ru/palm-jebel-ali-hotels";
import { howToBuyOffPlanRu } from "@/lib/content/i18n/ru/palm-jebel-ali-how-to-buy-off-plan";
import { marinasRu } from "@/lib/content/i18n/ru/palm-jebel-ali-marinas";
import { masterplanRu } from "@/lib/content/i18n/ru/palm-jebel-ali-masterplan";
import { mortgageRu } from "@/lib/content/i18n/ru/palm-jebel-ali-mortgage";
import { projectStatusRu } from "@/lib/content/i18n/ru/palm-jebel-ali-project-status";
import { rentalYieldRu } from "@/lib/content/i18n/ru/palm-jebel-ali-rental-yield";
import { resaleRu } from "@/lib/content/i18n/ru/palm-jebel-ali-resale";
import { schoolsRu } from "@/lib/content/i18n/ru/palm-jebel-ali-schools";
import { serviceChargesRu } from "@/lib/content/i18n/ru/palm-jebel-ali-service-charges";
import { villasRu } from "@/lib/content/i18n/ru/palm-jebel-ali-villas";
import { vsBluewatersRu } from "@/lib/content/i18n/ru/palm-jebel-ali-vs-bluewaters";
import { vsDistrictOneRu } from "@/lib/content/i18n/ru/palm-jebel-ali-vs-district-one";
import { vsDubaiIslandsRu } from "@/lib/content/i18n/ru/palm-jebel-ali-vs-dubai-islands";
import { vsEmaarBeachfrontRu } from "@/lib/content/i18n/ru/palm-jebel-ali-vs-emaar-beachfront";
import { vsJumeirahBayRu } from "@/lib/content/i18n/ru/palm-jebel-ali-vs-jumeirah-bay-island";
import { vsWorldIslandsRu } from "@/lib/content/i18n/ru/palm-jebel-ali-vs-the-world-islands";
import { paymentPlansRu } from "@/lib/content/i18n/ru/payment-plans";
import { porcelainRosesRu } from "@/lib/content/i18n/ru/porcelain-roses";
import { pricesRu } from "@/lib/content/i18n/ru/prices";
import { redAuroraRu } from "@/lib/content/i18n/ru/red-aurora";
import { redwoodRu } from "@/lib/content/i18n/ru/redwood";
import { rentPalmJebelAliRu } from "@/lib/content/i18n/ru/rent";
import { sunsetMirageRu } from "@/lib/content/i18n/ru/sunset-mirage";
import { vsPalmJumeirahRu } from "@/lib/content/i18n/ru/vs-palm-jumeirah";
import { waveCrestRu } from "@/lib/content/i18n/ru/wave-crest";

export const I18N_COMMUNITIES: Record<string, Partial<Record<Locale, HubContent>>> = {
  "palm-jebel-ali": { ar: communityAr, ru: communityRu },
};
export const I18N_RESIDENCES: Record<string, Partial<Record<Locale, HubContent>>> = {
  "baia-luna": { ar: baiaLunaAr, ru: baiaLunaRu },
  "beach-collection": { ar: beachCollectionAr, ru: beachCollectionRu },
  "bluejay": { ar: bluejayAr, ru: bluejayRu },
  "cobalt-beach": { ar: cobaltBeachAr, ru: cobaltBeachRu },
  "coral-collection": { ar: coralCollectionAr, ru: coralCollectionRu },
  "coral-dune": { ar: coralDuneAr, ru: coralDuneRu },
  "cyan-sky": { ar: cyanSkyAr, ru: cyanSkyRu },
  "ocean-whisper": { ar: oceanWhisperAr, ru: oceanWhisperRu },
  "palm-central": { ar: palmCentralAr, ru: palmCentralRu },
  "porcelain-roses": { ar: porcelainRosesAr, ru: porcelainRosesRu },
  "red-aurora": { ar: redAuroraAr, ru: redAuroraRu },
  "redwood": { ar: redwoodAr, ru: redwoodRu },
  "sunset-mirage": { ar: sunsetMirageAr, ru: sunsetMirageRu },
  "wave-crest": { ar: waveCrestAr, ru: waveCrestRu },
};
export const I18N_BUY: Record<string, Partial<Record<Locale, HubContent>>> = {
  "palm-jebel-ali": { ar: buyPalmJebelAliAr, ru: buyPalmJebelAliRu },
};
export const I18N_RENT: Record<string, Partial<Record<Locale, HubContent>>> = {
  "palm-jebel-ali": { ar: rentPalmJebelAliAr, ru: rentPalmJebelAliRu },
};
export const I18N_OFFPLAN: Record<string, Partial<Record<Locale, HubContent>>> = {
  "palm-jebel-ali": { ar: offplanPalmJebelAliAr, ru: offplanPalmJebelAliRu },
};
export const I18N_GUIDES: Record<string, Partial<Record<Locale, GuideContent>>> = {
  "palm-jebel-ali-foreign-buyers": { ar: foreignBuyersAr, ru: foreignBuyersRu },
  "palm-jebel-ali-golden-visa": { ar: goldenVisaAr, ru: goldenVisaRu },
  "palm-jebel-ali-investor-guide": { ar: investorGuideAr, ru: investorGuideRu },
  "palm-jebel-ali-location": { ar: locationAr, ru: locationRu },
  "nakheel-palm-jebel-ali-developer": { ar: developerAr, ru: developerRu },
  "palm-jebel-ali-amenities": { ar: amenitiesAr, ru: amenitiesRu },
  "palm-jebel-ali-beaches": { ar: beachesAr, ru: beachesRu },
  "palm-jebel-ali-construction-progress": { ar: constructionProgressAr, ru: constructionProgressRu },
  "palm-jebel-ali-dining": { ar: diningAr, ru: diningRu },
  "palm-jebel-ali-floor-plans": { ar: floorPlansAr, ru: floorPlansRu },
  "palm-jebel-ali-for-uk-buyers": { ar: forUkBuyersAr, ru: forUkBuyersRu },
  "palm-jebel-ali-fronds": { ar: frondsAr, ru: frondsRu },
  "palm-jebel-ali-handover-timeline": { ar: handoverTimelineAr, ru: handoverTimelineRu },
  "palm-jebel-ali-history": { ar: historyAr, ru: historyRu },
  "palm-jebel-ali-hotels": { ar: hotelsAr, ru: hotelsRu },
  "palm-jebel-ali-how-to-buy-off-plan": { ar: howToBuyOffPlanAr, ru: howToBuyOffPlanRu },
  "palm-jebel-ali-marinas": { ar: marinasAr, ru: marinasRu },
  "palm-jebel-ali-masterplan": { ar: masterplanAr, ru: masterplanRu },
  "palm-jebel-ali-mortgage": { ar: mortgageAr, ru: mortgageRu },
  "palm-jebel-ali-project-status": { ar: projectStatusAr, ru: projectStatusRu },
  "palm-jebel-ali-rental-yield": { ar: rentalYieldAr, ru: rentalYieldRu },
  "palm-jebel-ali-resale": { ar: resaleAr, ru: resaleRu },
  "palm-jebel-ali-schools": { ar: schoolsAr, ru: schoolsRu },
  "palm-jebel-ali-service-charges": { ar: serviceChargesAr, ru: serviceChargesRu },
  "palm-jebel-ali-villas": { ar: villasAr, ru: villasRu },
  "palm-jebel-ali-vs-bluewaters": { ar: vsBluewatersAr, ru: vsBluewatersRu },
  "palm-jebel-ali-vs-district-one": { ar: vsDistrictOneAr, ru: vsDistrictOneRu },
  "palm-jebel-ali-vs-dubai-islands": { ar: vsDubaiIslandsAr, ru: vsDubaiIslandsRu },
  "palm-jebel-ali-vs-emaar-beachfront": { ar: vsEmaarBeachfrontAr, ru: vsEmaarBeachfrontRu },
  "palm-jebel-ali-vs-jumeirah-bay-island": { ar: vsJumeirahBayAr, ru: vsJumeirahBayRu },
  "palm-jebel-ali-vs-the-world-islands": { ar: vsWorldIslandsAr, ru: vsWorldIslandsRu },
  "palm-jebel-ali-payment-plans": { ar: paymentPlansAr, ru: paymentPlansRu },
  "palm-jebel-ali-prices": { ar: pricesAr, ru: pricesRu },
  "palm-jebel-ali-vs-palm-jumeirah": { ar: vsPalmJumeirahAr, ru: vsPalmJumeirahRu },
};

const ALL_MAPS = [I18N_COMMUNITIES, I18N_RESIDENCES, I18N_BUY, I18N_RENT, I18N_OFFPLAN, I18N_GUIDES];

// Which non-English locales exist for a given base slug (any type).
export function translatedLocales(slug: string): Locale[] {
  const c = ALL_MAPS.map((m) => m[slug]).find(Boolean);
  const out: Locale[] = [];
  if (c?.ar) out.push("ar");
  if (c?.ru) out.push("ru");
  return out;
}
